// BILL_LIST
export const SEARCH_BILL_LIST = 'SEARCH_BILL_LIST'
export const SEARCH_STUDENT_BILL_LIST = 'SEARCH_STUDENT_BILL_LIST'
export const SEARCH_PRINT_BILL_LIST = 'SEARCH_PRINT_BILL_LIST'
export const PRINT_BILL_LIST = 'PRINT_BILL_LIST'
export const EXPORT_BILL_LIST = 'EXPORT_BILL_LIST'
// BILL
export const SEARCH_RECENT_BILL = 'SEARCH_RECENT_BILL'
export const ADD_BILL = 'ADD_BILL'
export const EDIT_BILL = 'EDIT_BILL'
export const REMOVE_BILL = 'REMOVE_BILL'
export const CONFIRM_BILL = 'CONFIRM_BILL'